### ISSUE TITLE
Color of text in disabled inputs rely on the browser's default settings 

### ISSUE THREAD

**Issue by danoc** [optimizely/lego#117]
We have a class `.lego-input--disabled` that sets the background of an element to the color of a disabled form. @mikeng13 needed to use that class because of CodeMirror, but the text in his fake input was not the same as the disabled form inputs.

![pasted image at 2015_09_04 11_01 am](https://cloud.githubusercontent.com/assets/916038/9691055/e79cb498-52f4-11e5-946a-95cfd9cbea84.png)

We should set a color on the disabled form inputs to fix this.

**Comment by danoc** [comment]
@tomgenoni, @kwalker3690 – What do you think?

**Comment by kwalker3690** [comment]
sounds good to me

**Comment by tomgenoni** [comment]
https://github.com/optimizely/lego/pull/124
