### ISSUE TITLE
Add focus state to buttons 

### ISSUE THREAD

**Issue by kwalker3690** [optimizely/lego#132]
It's currently nearly impossible to understand what's happening tab through our buttons, and we should change this for accessibility purposes. Some ideas: http://a11yproject.com/posts/never-remove-css-outlines/

**Comment by tomgenoni** [comment]
Dupe of https://github.com/optimizely/lego/issues/89 Does this suffice?

**Comment by kwalker3690** [comment]
Oopsies yep!
