### ISSUE TITLE
Rethink how the `.lego-pane` (and other layout) classes work

### ISSUE THREAD

**Issue by danoc** [optimizely/lego#70]
Should we continue trying to abstract them since all of the methods are so different and can be easily confused.

Off the top of my head, I can think of the following classes that this relates to:
* `.lego-pane`
* `.full-screen`

**Comment by tomgenoni** [comment]
How about...

```
.lego-layout--row {
  @include display(flex);
}

.lego-layout--column {
  @include display(flex);
  @include flex-direction(column);
  min-height: 0;
}

.lego-layout__flex--1 {
  @include flex(1);
}

.lego-layout__flex--none {
  @include flex(none);
}

.lego-layout__center {
  @include align-items(center);
}

.lego-layout__self--start {
  @include align-self(start);
}

.lego-layout__self--center {
  @include align-self(center);
}

.lego-layout__self--end {
  @include align-self(end);
}
```

**Comment by danoc** [comment]
@tomgenoni – What about properties like `justify-content`?

Also, I feel like `align-self` is rarely needed so providing `.lego-layout__self--end` without a `.lego-layout__row--end` would encourage people to use a bunch of `align-self` properties on children instead of `align-items` on the parent.

**Comment by tomgenoni** [comment]
`align-items` on the parent is accomplished with `lego-layout--row--center`

**Comment by danoc** [comment]
Right, but I guess I'm asking why we provide `.lego-layout__self--end` but not `.lego-layout--row--end`, for example.

**Comment by tomgenoni** [comment]
What would `.lego-layout--row--end` do? `.lego-layout__self--*` aligns a child to top/center/bottom.

**Comment by danoc** [comment]
How about:

```
.lego-layout--row {
  @include display(flex);
}

.lego-layout--column {
  @include display(flex);
  @include flex-direction(column);
  min-height: 0;
}

.lego-layout--greedy {
  @include flex(1);
}

.lego-layout--lazy {
  @include flex(none);
}

.lego-layout--center {
  @include align-items(center);
}

.lego-layout--start {
  @include align-items(start);
}

.lego-layout--end {
  @include align-items(end);
}

.lego-layout--justified--center {
  @include justify-content(center);
}

.lego-layout--justified--start {
  @include justify-content(flex-start);
}

.lego-layout--justified--end {
  @include justify-content(flex-end);
}

.lego-layout--justified {
  @include justify-content(space-between);
}

.lego-layout--justified--around {
  @include justify-content(space-around);
}

.lego-layout--self--start {
  @include align-self(start);
}

.lego-layout--self--center {
  @include align-self(center);
}

.lego-layout--self--end {
  @include align-self(end);
}

.lego-layout--self--stretch {
  @include align-self(stetch);
}

.lego-layout--wrap {
  @include flex-wrap(wrap);
}

.lego-layout--wrap--reverse {
  @include flex-wrap(wrap-reverse);
}
```

**Comment by tomgenoni** [comment]
hmm, not sure we need all those, like `wrap` and `stretch`. Also, I like `lazy` but the naming will be inconsistent going from actual flexbox names to made-up names.

**Comment by tomgenoni** [comment]
+ @kwalker3690

I thought about this for a while and I think I've been overthinking it. My original plan was to have a set of classes reserved for page layouts so developers could quickly tell what was going on. Then we had the flexbox changes that required `min-height/width: 0` so it seemed like a good idea to keep them separate from "normal" flexbox classes. But...

- what is a page layout anyway? It's hard to know when/where to use them vs non-layout classes.
- there is currently a lot of duplication: mixins, flexbox classes, layout classes
- should the non-layout classes contain the `min-height/width` "fix"?

I think it would make things easier if we:

- only had one set of classes and one set of mixins
- included the `min-height/width` fix by default. In the rare case that this causes an issue we can override either with trump classes or provide a flag in the mixin to exclude the min-height/width.

So maybe:

`@include display(flex, $flex-fix: false)`

```
.flex {
  @include display(flex); // min-height/width: 0; would be included here. 
}

.flex--row {
  @include display(flex);
  @include flex-direction(row);
}

.flex--column {
  @include display(flex);
  @include flex-direction(column);
}

.flex--1 {
  @include flex(1);
}

.flex--0 {
  @include flex(none);
}

.flex-align--center {
  @include align-items(center);
}

.flex-align--start {
  @include align-items(start);
}

.flex-align--end {
  @include align-items(end);
}

.flex-justified--center {
  @include justify-content(center);
}

.flex-justified--start {
  @include justify-content(flex-start);
}

.flex-justified--end {
  @include justify-content(flex-end);
}

.flex-justified--between {
  @include justify-content(space-between);
}

.flex-justified--around {
  @include justify-content(space-around);
}

.flex-self--start {
  @include align-self(start);
}

.flex-self--center {
  @include align-self(center);
}

.flex-self--end {
  @include align-self(end);
}

.flex-self--stretch {
  @include align-self(stetch);
}

.flex-wrap {
  @include flex-wrap(wrap);
}

.flex-wrap--reverse {
  @include flex-wrap(wrap-reverse);
}
```

**Comment by kwalker3690** [comment]
I totally agree with this move. I think it was overkill to have the two sets of classes that do super similar things, in fact I almost never used the lego-pane classes when we had them and just used the flex classes anyways. This is particularly true because of how we build our pages, with components, and that these components can be swapped in and out with each other, so your question of "what is a page layout" is right on the money. Particularly with p13n we're getting farther and farther away from strict "pages", so I think this idea follows that nicely.

**Comment by danoc** [comment]
Talked about this with @tomgenoni in person, but LGTM!

**Comment by tomgenoni** [comment]
Ok, fantastic. Relieved to be finally done with this pain point. I will introduce this a breaking change.

**Comment by kwalker3690** [comment]
This is the most excited @tomgenoni has ever been.

**Comment by danoc** [comment]
PR is here: https://github.com/optimizely/lego/pull/108
