### ISSUE TITLE
Update the buttons to reflect the new styles

### ISSUE THREAD

**Issue by danoc** [optimizely/lego#92]
Creating this ticket to track @kwalker3690's work on buttons.

**Comment by danoc** [comment]
@kwalker3690 – How has the progress been on this?

**Comment by kwalker3690** [comment]
@danoc Great! I'm working with Linda to finalize the styles. They can be seen rendered here, we've almost finalized them: http://optimizely.github.io/proto/lego-v2/

**Comment by danoc** [comment]
Closing since it's merged.
