### ISSUE TITLE
gitignore has old content that exists from old js build

### ISSUE THREAD

**Issue by chestone** [optimizely/lego#97]
We should clean this up so anyone that has an old branch(such as myself) doesn't commit js accidentally.

**Comment by danoc** [comment]
@chestone – Did you clean this up already?

**Comment by tomgenoni** [comment]
@danoc do you know what we should remove?

```
node_modules
dist
.bundle
.sass-cache
npm-debug.log
.DS_Store
```

**Comment by danoc** [comment]
Looks fine to me. I think we should just keep it as-is.
